# inventory/prod.ini
# Production environment inventory

[bastion]
prod-bastion ansible_host=<PROD_BASTION_IP> ansible_user=ansible

[bastion:vars]
env=prod
gke_cluster_name=myapp-prod-gke
gke_region=us-central1
gcp_project_id=<PROD_PROJECT_ID>

[k8s_config]
localhost ansible_connection=local

[k8s_config:vars]
env=prod
